{
 "title": "Real-Time Space Monitoring Dashboard",
 "time": { "from": "2020-10-06T19:27:31.167Z", "to": "2020-10-07T07:27:31.167Z" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   {
    "name": "name",
    "label": "Hostname:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "node_exporter"
    },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "prometheus"
    },
    {
     "expr": "up{job=\"rtms\"}",
     "legendFormat": "rtms"
    }
   ]
  },
  { "title": "Basic CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"localhost:9100\",job=~\"node_exporter\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"localhost:9100\",job=~\"node_exporter\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"localhost:9100\",job=~\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_active_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_total_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{instance=~\"localhost:9100\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_inactive_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Inactive - Memory which has been less recently used."
    },
    {
     "expr": "node_memory_active_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Active - Memory that has been used more recently."
    }
   ]
  },
  { "title": "Basic CPU / Mem Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  { "title": "Critical Systems Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power Supply ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "system_temp_celsius{component=\"power_supply\"}",
     "legendFormat": "Power Supply Temp"
    }
   ]
  },
  {
   "title": "SC Die",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "SC_temperature_celsius", "legendFormat": "die Temp" }
   ]
  },
  {
   "title": "IMU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "system_temp_celsius{component=\"IMU\"}",
     "legendFormat": "IMU Temp"
    }
   ]
  },
  { "title": "Voltage and Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Zynq Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "SC_zynq_voltage", "legendFormat": "zynq voltage" }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "rate(power_supply_joules[5m])" }
   ]
  },
  { "title": "Orientation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Euler Vectors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_orientation_eulers{euler_axis=\"eulerX\"}",
     "legendFormat": "eulerX"
    },
    {
     "expr": "system_orientation_eulers{euler_axis=\"eulerY\"}",
     "legendFormat": "eulerY"
    },
    {
     "expr": "system_orientation_eulers{euler_axis=\"eulerZ\"}",
     "legendFormat": "eulerZ"
    }
   ]
  },
  {
   "title": "Quaternions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_orientation_quaternions{quaternion_axis=\"quatA\"}",
     "legendFormat": "quatA"
    },
    {
     "expr": "system_orientation_quaternions{quaternion_axis=\"quatB\"}",
     "legendFormat": "quatB"
    },
    {
     "expr": "system_orientation_quaternions{quaternion_axis=\"quatC\"}",
     "legendFormat": "quatC"
    },
    {
     "expr": "system_orientation_quaternions{quaternion_axis=\"quatD\"}",
     "legendFormat": "quatD"
    }
   ]
  },
  { "title": "Acceleration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Acceleration Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_acceleration_omegas{omega_axis=\"omegaX\"}",
     "legendFormat": "OmegaX"
    },
    {
     "expr": "system_acceleration_omegas{omega_axis=\"omegaY\"}",
     "legendFormat": "OmegaY"
    },
    {
     "expr": "system_acceleration_omegas{omega_axis=\"omegaZ\"}",
     "legendFormat": "OmegaZ"
    }
   ]
  },
  {
   "title": "Arbitrary Analog and Digital Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "Analog Pin Outputs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_analog{analog_pins=\"a0\"}",
     "legendFormat": "analog_pin a0"
    },
    {
     "expr": "system_analog{analog_pins=\"a1\"}",
     "legendFormat": "analog_pin a1"
    },
    {
     "expr": "system_analog{analog_pins=\"a2\"}",
     "legendFormat": "analog_pin a2"
    },
    {
     "expr": "system_analog{analog_pins=\"a3\"}",
     "legendFormat": "analog_pin a3"
    }
   ]
  },
  {
   "title": "Digital Pin (Boolean) Outputs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_digital{digital_pins=\"d0\"}",
     "legendFormat": "digital_pin d0"
    },
    {
     "expr": "system_digital{digital_pins=\"d1\"}",
     "legendFormat": "digital_pin d1"
    },
    {
     "expr": "system_digital{digital_pins=\"d2\"}",
     "legendFormat": "digital_pin d2"
    },
    {
     "expr": "system_digital{digital_pins=\"d3\"}",
     "legendFormat": "digital_pin d3"
    }
   ]
  }
 ]
}